### ISSUE TITLE
Unnecessary Input Params

### ISSUE THREAD

**Issue by mdconaway** [joey8williams/querybuddy#1]
Isn't it possible to infer ```selectorType ``` in most of these functions by using a W3C compliant regular expression against the  ```selectorValue```? (Or some derivative of how jQuery determines how to query the DOM based on string input?)

It seems like allowing a user to manually specify the selector type can lead to input divergence where a selector value cannot possibly match the provided selector type.

**Comment by jowi-dev** [comment]
The original intent is to replace writing something like "input[class='className']" with a more concise, less error prone method. Are you referring to something like querySelectorAll("input.className") ? 

One consideration is using something like querySelectorAll(selectorType) and .filter(node => node.selectorType == selectorValue)  if there are any returned results, although conceptually it trades off efficiency for safety.

**Comment by mdconaway** [comment]
For the case you outlined, the jQuery approach would be a selector string of ```input.className```.

Generally speaking, the jQuery approach is to use css-style selectors.  This is a fairly good approach to take, and you can still detect what style of DOM functions to interact with by running a regex that determines the DOM query interface based on the regex match of the input string.

So a regex that matches ```input.className``` (probably by detecting no ```#```, and detecting a ```.```) would use the querySelector or querySelectorAll method, while anything that matched an id-style syntax could use getElementById.

Additionally, you could replace the ```selectorType``` input parameter with something more like a ```limit``` parameter that could splice down the result set to whatever length the caller specifies.  This ```limit``` value can then also identify the scenario whereby a user actually wants to use ```querySelector``` instead of ```querySelectorAll``` by simply detecting a passed in limit of 1.

**Comment by jowi-dev** [comment]
You're right, that's definitely worth looking into. I'll leave this open there's until a new commit. Thanks!

**Comment by Adola** [comment]
@mdconaway, I made a fork of this project that resolves this issue.
